### ISSUE TITLE
Click to Space + Enter, not checking texts

### ISSUE THREAD

**Issue by bilimtekno** [anschwa/typing-test#2]
Hello, 
In text area if you click Space+enter, not checking correct or wrong, you can write ultra fastly :)

**Comment by anschwa** [comment]
That's a great find! 
I wasn't getting very high WPM with that method, but now it will count the word as incorrect if you manage to skip over it. http://anschwa.com/typing-test/

**Comment by bilimtekno** [comment]
Great work. Thanks.

**Comment by bilimtekno** [comment]
And is that possible to contact with you via email?
